global using Contracts.Business.Entities;
global using Domains.Entities;
global using eShopOnlineBusiness.Abstracts;
global using eShopOnlineBusiness.LogMessages;
global using eShopOnlineBusiness.Parameters;
global using Microsoft.Extensions.Logging;
global using Shared.DTOs.Inputs.FromBody.CreationDtos;
global using Shared.DTOs.Inputs.FromBody.UpdateDtos;
global using Shared.DTOs.Outputs.EntityDtos;
